using UnityEngine;
using System;
using GamePlay;
using static GamePlay.CharacterState;
using static Managers.Properties;
using Random = UnityEngine.Random;

public class EnemiesGenerator : MonoBehaviour
{
    [SerializeField] private float sendTimer = 0;
    [SerializeField] private float frequency = ENEMY_FREQUENCY;
    [SerializeField] private bool noEnemyMode;
    [SerializeField] private GameObject parent;
    [SerializeField] private CharacterState currentCharacterState;

    public GameObject myEnemy;
    public GameObject myObstacle;
    public GameObject mainCharacter;

    private bool started;
    private float minRange;
    private float maxRange;

    void Awake()
    {
        noEnemyMode = false;
        parent = GameObject.FindGameObjectWithTag("AutoGenerated");
        UpdateCurrentCharacterState();
        GameManager.onGameStateChanged += StartGame;
    }

    private void OnDestroy()
    {
        GameManager.onGameStateChanged -= StartGame;
    }

    void StartGame(State state)
    {
        started = state == State.PLAY;
    }

    // Update is called once per frame
    void Update()
    {
        UpdateCurrentCharacterState();
        if (started)
        {
            // Create no enemies in cheat mode
            if (!noEnemyMode)
            {
                SendEnemies();
            }
        }
    }

    /// <summary>
    /// Send Enemies to the game play
    /// </summary>
    private void SendEnemies()
    {
        sendTimer -= Time.deltaTime;
        //enemies will be sent when the timer reach 0, then reset the timer = frequency
        if (sendTimer <= 0)
        {
            GenerateEnemies();
            sendTimer = frequency;
        }
    }

    /// <summary>
    /// Generate the enemies based on the character current line
    /// </summary>
    /// <exception cref="ArgumentOutOfRangeException"></exception>
    private void GenerateEnemies()
    {
        switch (currentCharacterState)
        {
            case MIDDLE:
                CreateEnemies(Random.value > 0.5f ? ENEMY_LEFT : ENEMY_RIGHT);
                break;
            case LEFT:
                CreateEnemies(ENEMY_LEFT);
                break;
            case RIGHT:
                CreateEnemies(-ENEMY_RIGHT);
                break;
            case DEAD:
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    /// <summary>
    /// Toggle No Enemy Mode
    /// </summary>
    public void ToogleNoEnemyMode()
    {
        noEnemyMode = !noEnemyMode;
    }


    /// <summary>
    /// Create enemies 
    /// </summary>
    private void CreateEnemies(float xPos)
    {
        //yPos will be random generated between minRange & maxRange
        var yPos = Random.Range(ENEMY_YPOS_MIN, ENEMY_YPOS_MAX);
        transform.position = new Vector3(xPos, yPos, 40f);
        Instantiate(myEnemy, transform.position, transform.rotation, parent.transform);
    }

    /// <summary>
    /// Update current State of the character
    /// </summary>
    private void UpdateCurrentCharacterState()
    {
        if (mainCharacter != null)
        {
            currentCharacterState = mainCharacter.GetComponent<CharacterController>().currentState;
        }
    }
}